### ISSUE TITLE
[Request] Combine partial item stacks when sorting

### ISSUE THREAD

**Issue by LaserLag** [end360/Valheim-Inventory-Sorting#1]
It would be nice if partial item stacks were combined when sorting.

For example, if you had a stack of 7 wood and a stack of 22 wood in a chest, pressing "Sort" should add them together into 1 stack. This currently doesn't happen - they are just moved next to each other.

**Comment by end360** [comment]
I've created the feature and plan on releasing it soon after I do some more extensive tests tomorrow. If you'd like to test it out in the meantime I published a beta release in the Github repo titled "v1.1.0 beta". You can download the zip file from that and import it locally into r2modman
