### ISSUE TITLE
[Bug/Request] Sort bound to left on L-Stick for controller?

### ISSUE THREAD

**Issue by Outwise** [end360/Valheim-Inventory-Sorting#2]
the controller requires using the left stick to navigate through the inventory, which means trying to move left to the first position evokes the sort function a ton, lagging out the game.

Could you change this binding? I think x or y are safe, they dont currently do anything in the inventory (ideally valheim will add a controller equivalent for Ctrl+Click "one-click-move-stack" command, but nothing bound yet)

**Comment by Kobox** [comment]
Hello, I came to say the same. 
X is to eat food and Y is to open/close the inventory. I guess a combo would be better for that? Something like LB+RB, or L3+R3? 
Thank you for the  mod by the way!

**Comment by end360** [comment]
I will look into this. I do not currently have any sort of controller to test this out with but I've been meaning to get one so this is a good excuse to buy one. Once I get one I can work on this issue better.
